### ISSUE TITLE
Venta. Informe: Recibos del Cliente.

### ISSUE THREAD

**Issue by sebatista** [marionumza/EA#8]
El recibo de pago obtenido desde Contabilidad -> Ventas -> Pagos. Eligiendo un pago de un cliente e imprimiendo se obtiene el siguiente archivo.
[Recibo de Pago.pdf](https://github.com/marionumza/EA/files/4172305/Recibo.de.Pago.pdf)

El código del documento es: CUST.IN/2020/0001.

A pesar de tener configurado el código: RE-X REC EAN X00000001.

**Comment by marionumza** [comment]
Hay que instalar el reporte de la localiacion argentina para pagos y levantar el servicio aeroo
[Recibo 0001-00000001.pdf](https://github.com/marionumza/EA/files/4178813/Recibo.0001-00000001.pdf)
